version: "0.0.1"
services:
  template:
    image: template:latest
    container_name: template
    restart: always
    # volumes:
    # - /leaper/test/template/data/logs:/app/lgos
    ports:
      - "8000:8000"
    networks:
      - leaper
      # environment:
      # - RTS_MYSQL_HOST=192.168.5.59
      # - RTS_MYSQL_PORT=3306
      # - RTS_MYSQL_USER=root
      # - RTS_MYSQL_PASSWORD=Leaper@123
      # - NODE_ENV=production

networks:
  leaper:
    external: true
